project:
  type: book

book:
  title: "quartotest"
  author: "Norah Jones"
  date: "09/05/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



