name: Build and Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy with Composite Action
        uses: rahuketu86/workflows/quarto-deploy@main
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          minio_endpoint: ${{ secrets.MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: gitpages
          target_dir: /quartotest.app.beast.local
          source_dir: _book